Improved LICENSE.txt
dojo/dojo-website pull request #53
Opened 2020-09-30 18:47 UTC by yashmit178

2020-09-30 23:55 UTC, dylans requested changes
Thanks. These changes made me realize we need a few other changes

* JS Foundation -> OpenJS Foundation in several places
* 2017 -> 2020

Let me know if you'd like to make these changes. If not I'll do so in a separate PR.

2020-09-30 23:55 UTC, dylans commented on LICENSE.txt
>  without prior written consent from the JS Foundation.
```suggestion
without prior written consent from the OpenJS Foundation.
```

2020-10-01 03:20 UTC, yashmit178 commented
Will be keen to do the same, thanks for the opportunity Dylan

On Thu, Oct 1, 2020 at 5:25 AM Dylan Schiemann <notifications@github.com>
wrote:

> *@dylans* requested changes on this pull request.
>
> Thanks. These changes made me realize we need a few other changes
>
>    - JS Foundation -> OpenJS Foundation in several places
>    - 2017 -> 2020
>
> Let me know if you'd like to make these changes. If not I'll do so in a
> separate PR.
> ------------------------------
>
> In LICENSE.txt
> <https://github.com/dojo/dojo-website/pull/53#discussion_r497862427>:
>
> >  Foundation and are not licensed for use. Designs and CSS from
>
> -dojo-website may not be used on any site, personal or commercial,
>
> +dojo-website may not be used on any site for personal or commercial use
>
>  without prior written consent from the JS Foundation.
>
>
> ⬇️ Suggested change
>
> -without prior written consent from the JS Foundation.
>
> +without prior written consent from the OpenJS Foundation.
>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dojo/dojo-website/pull/53#pullrequestreview-499899414>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQY3L4EVJ7J4SGZEB7DLP7TSIPAOPANCNFSM4R7ONHUQ>
> .
>

2020-10-01 20:27 UTC, dylans approved these changes

2020-10-01 20:28 UTC, merged

2020-10-01 20:28 UTC, dylans commented
Thanks @yashmit178!

2020-10-02 03:18 UTC, yashmit178 commented
i should thank you as you gave me an opportunity to build my proile and i
felt so motivated after helping you.

On Fri 2 Oct, 2020 1:58 am Dylan Schiemann, <notifications@github.com>
wrote:

> Thanks @yashmit178 <https://github.com/yashmit178>!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/dojo/dojo-website/pull/53#issuecomment-702378932>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQY3L4EXNHWTYGLJLU65QG3SITQ6XANCNFSM4R7ONHUQ>
> .
>